In [2]:
%autosave 120

Autosaving every 120 seconds


In [ ]:
# Numpy Assignment Questions

In [ ]:
# 1. What is a Python library? Why do we use Python libraries?

# A Python library is a collection of precompiled code that can be used to perform common tasks, functions, or operations. It includes modules, functions, and classes. Libraries help developers reuse code, simplify tasks, and focus on the main logic of their programs without having to write everything from scratch.

# We use Python libraries to save time, reduce errors, and enhance efficiency by leveraging pre-written code for common tasks like data manipulation, mathematical operations, and more.

In [ ]:
# 2. What is the difference between Numpy array and List?

# Numpy Array:
# Requires the installation of the numpy package.
# Supports efficient operations like element-wise computations, matrix manipulations, and more.
# Homogeneous: All elements must be of the same data type.
# Uses less memory and provides faster operations.

# List:
# Built-in data structure in Python.
# Can store elements of different data types.
# Operations are slower compared to Numpy arrays due to its generalized structure.
# More flexible in handling a variety of data types.

In [3]:
# 3. Find the shape, size and dimension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Finding shape, size, and dimension
shape = arr.shape
size = arr.size
dimension = arr.ndim

print("Shape:", shape)
print("Size:", size)
print("Dimension:", dimension)

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimension:", arr.ndim)


Shape: (3, 4)
Size: 12
Dimension: 2
Shape: (3, 4)
Size: 12
Dimension: 2


In [4]:
# 4. Write python code to access the first row of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Accessing the first row
first_row = arr[0]
print(first_row)

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[0])


[1 2 3 4]
[1 2 3 4]


In [5]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Accessing the element at the third row and fourth column
element = arr[2, 3]
print(element)

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[2, 3])


12
12


In [6]:
# 6. Write code to extract all odd-indexed elements from the given numpy array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Extracting all odd-indexed elements
odd_elements = arr[:, 1::2]
print(odd_elements)

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[:, 1::2])


[[ 2  4]
 [ 6  8]
 [10 12]]
[[ 2  4]
 [ 6  8]
 [10 12]]


In [7]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

import numpy as np

# Generating a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)
print(random_matrix)

print(np.random.rand(3, 3))


[[0.6922391  0.21927107 0.49266051]
 [0.92160528 0.64622541 0.79648413]
 [0.54699149 0.62775424 0.5085198 ]]
[[0.78358722 0.96025078 0.35485277]
 [0.52215608 0.4378894  0.67355608]
 [0.38884556 0.87574558 0.82035884]]


In [9]:
# 8. Describe the difference between np.random.rand and np.random.randn?

# np.random.rand: Generates random numbers from a uniform distribution between 0 and 1. All numbers have an equal chance of being chosen.

# np.random.randn: Generates random numbers from a standard normal distribution (mean 0, variance 1). The numbers are distributed with a bell curve, so values closer to 0 are more likely than values farther away from 0.

In [10]:
# 9. Write code to increase the dimension of the following array?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Increasing dimension of the array
new_arr = np.expand_dims(arr, axis=0)
print(new_arr)
print(new_arr.shape)  # To check the new shape

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
new_arr = np.expand_dims(arr, axis=0)
print(new_arr)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
(1, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [12]:
# 10. How to transpose the following array in NumPy?
# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Transposing the array
transposed_arr = arr.T
print(transposed_arr)

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr.T)


[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [16]:
# 11. Consider the following matrix:
# Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Perform the following operation using Python1

# 1.Index wise multiplication
index_wise_mult = A * B
print("Index-wise multiplication:\n", index_wise_mult)
print(A * B)


# 2.Matrix multiplication
matrix_mult = np.dot(A, B.T)
print("Matrix multiplication:\n", matrix_mult)
print(np.dot(A, B.T))


# 3.Add both the matricK

matrix_add = A + B
print("Matrix addition:\n", matrix_add)
print(A + B)

# 4.Subtract matrix B from  A
matrix_sub = A - B
print("Matrix subtraction:\n", matrix_sub)
print(A - B)

# 5.Divide Matrix B by A
matrix_div = B / A
print("Matrix division:\n", matrix_div)
print(B / A)



Index-wise multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Matrix addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Matrix subtraction:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Matrix division:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
# 12. Which function in Numpy can be used to swap the byte order of an array?

import numpy as np

arr = np.array([1, 256, 512], dtype='>i4')  # Big-endian byte order
swapped_arr = arr.byteswap()
print(swapped_arr)

arr = np.array([1, 256, 512], dtype='>i4')
print(arr.byteswap())


# The function np.ndarray.byteswap() is used to swap the byte order of an array. This is useful when dealing with data that has different byte orders, like when reading data from files produced on machines with different architectures.

[16777216    65536   131072]
[16777216    65536   131072]


In [19]:
# 13. What is the significance of the np.linalg.inv function?

import numpy as np

A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)
print(A_inv)

A = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(A))

# The np.linalg.inv() function is used to compute inverse of square matrix. The inverse of matrix a is the A^-1 such that A*A^-1 = I is the identity matrix. 
# Inverting a matrix is commonly used in solving linear equations, where A*X = B can be solved for X as X = A^-1

[[-2.   1. ]
 [ 1.5 -0.5]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [20]:
# 14. What does the np.reshape function do, and how is it used?

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.reshape(2, 3))

# The np.reshape() function in Numpy changes the shape of an existing array without altering its data. It returns a new array with the specified dimensions.
# The product of the new shape's dimensions must equal the total number of elements in the original array.

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
# 15. What is broadcasting in Numpy?

# Broadcasting is a mechanism in Numpy that allows arrays of different shapes to be combined in arithmetic operations. Instead of creating multiple copies of an array, Numpy "broadcasts" the smaller array across the larger array so that they have compatible shapes.
# Broadcasting simplifies code and enhances performance by avoiding explicit duplication of data in memory.

import numpy as np

A = np.array([1, 2, 3])
B = np.array([[1], [2], [3]])

result = A + B  # Broadcasting occurs here
print(result)
